version: '1.0'

services:
  imlsreact:
    image: imlsreact
    build:
      context: ./fe2
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
  fastapiserver:
    image: fastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      SERVER_PORT: 5001
    ports:
      - 5001:5001
    depends_on:
      - imlsreact
