[project]
name = "open-metadata-exchange"
version = "0.1.0"
requires-python = ">= 3.11"

classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
optional-dependencies.docs = [
  "furo",
  "myst-parser",
  "rst-to-myst[sphinx]",
  "sphinx-autoapi",
  "sphinxcontrib-mermaid",
]

[tool.codespell]
ignore-words-list = "formend,socio-economic"
skip = "*/package-lock.json"
