name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  inn-docker:
    strategy:
      fail-fast: false
      max-parallel: 1  # Avoid port contention
      matrix:
        service-image: [cclauss/inn, greenbender/inn]
    runs-on: ubuntu-latest
    services:
      inn-service:
        image: ${{ matrix.service-image }}
        ports:
          - 119:119
          - 563:563
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: python src/nntplib_tests.py || true
      - run: python src/nntp_io.py
      - run: pip install --upgrade pip
      - run: pip install pydantic pynntp pytest
      - run: pytest
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.1
